name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Fazer checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar o .NET 8
    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # 3. Restaurar dependências do projeto
    - name: Restore dependencies
      run: dotnet restore

    # 4. Construir o projeto
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # 5. Rodar os testes com string de conexão de teste
    - name: Run tests
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Pooling=true;Database=db_pos_fase_1;User Id=admin;Password=1234;"
      run: dotnet test --no-build --verbosity normal
      working-directory: ./POS_TECH_FIAP_TECH_CHALLENGE_FASE_1/TESTES_POS_TECH_FASE_UM

    # 6. Logar no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Construir a imagem Docker
    - name: Build Docker image
      run: docker build -t sfbarcelos/pos_tech_fase_um_image:latest .

    # 8. Fazer push da imagem para o Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push sfbarcelos/pos_tech_fase_um_image:latest
