name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: db_pos_fase_1
        options: >-
          --health-cmd="pg_isready -U admin" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # 1. Verificar dependências no runner self-hosted
      - name: Verificar dependências do runner
        run: |
          echo "Verificando se Docker está instalado..."
          docker --version || (echo "Docker não está instalado" && exit 1)
          echo "Verificando se psql está instalado..."
          psql --version || (echo "PostgreSQL client (psql) não está instalado" && exit 1)
          echo "Verificando se .NET SDK está instalado..."
          dotnet --version || (echo ".NET SDK não está instalado" && exit 1)

      # 2. Fazer checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 3. Configurar .NET 8
      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 4. Restaurar dependências do projeto
      - name: Restaurar dependências
        run: dotnet restore

      # 5. Construir o projeto
      - name: Construir o projeto
        run: dotnet build --configuration Release --no-restore

      # 6. Executar os testes
      - name: Executar testes
        env:
          ConnectionStrings__DefaultConnection: "Host=127.0.0.1;Port=5432;Pooling=true;Database=db_pos_fase_1;User Id=admin;Password=1234;"
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ github.workspace }}/TESTES_POS_TECH_FASE_UM

      # 7. Fazer login no Docker Hub
      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Construir a imagem Docker
      - name: Construir a imagem Docker
        run: docker build -t sfbarcelos/pos_tech_fase_um_image:latest .

      # 9. Fazer push da imagem para o Docker Hub
      - name: Fazer push da imagem para o Docker Hub
        run: docker push sfbarcelos/pos_tech_fase_um_image:latest

